image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


build-gateway:
  stage: build
  script:
    gradle lab-template:gateway:assemble lab-template:gateway:testClasses

checkStyle-gateway:
  stage: staticAnalysis
  script:
    gradle lab-template:gateway:checkstyleMain lab-template:gateway:checkStyleTest
  allow_failure: true


PMD-gateway:
  stage: staticAnalysis
  script:
    gradle lab-template:gateway:pmdMain
  allow_failure: true

test-gateway:
  stage: test
  script:
    - gradle lab-template:gateway:test lab-template:gateway:jacocoTestReport
  coverage: /([0-9]{1,3})%/
