image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"


build-authentication-microservice:
  stage: build
  script:
    gradle lab-template:authentication-microservice:assemble lab-template:authentication-microservice:testClasses

checkStyle-authentication-microservice:
  stage: staticAnalysis
  script:
    gradle lab-template:authentication-microservice:checkstyleMain lab-template:authentication-microservice:checkStyleTest
  allow_failure: true

PMD-authentication-microservice:
  stage: staticAnalysis
  script:
    gradle lab-template:authentication-microservice:pmdMain
  allow_failure: true

test-authentication-microservice:
  stage: test
  script:
    - gradle lab-template:authentication-microservice:test lab-template:authentication-microservice:jacocoTestReport
    - cat lab-template/authentication-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
